name: candy_mon
description: "CandyMon - juego match-3 (TP2 Laboratorio Orientado a Aplicaciones Moviles)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Motor de juego (Plan A)
  flame: ^1.18.0
  # Manejo de estado global (usuario, diamantes, tema)
  provider: ^6.1.2
  # Persistencia local -> funciona 100% offline / modo avion
  shared_preferences: ^2.2.3
  # Musica y efectos de sonido (offline)
  flame_audio: ^2.12.2
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Genera el icono de la app (Android) y el favicon (web)
  flutter_launcher_icons: ^0.14.1

# Configuracion del icono: correr  dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/pokeball_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/pokeball_icon.png"
    background_color: "#E3350D"
    theme_color: "#E3350D"

flutter:
  uses-material-design: true
  # Imagenes de las piezas: charizard, pikachu, venusaur, blastoise, gengar, snorlax (.png)
  assets:
    - assets/images/
    - assets/audio/
